default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^\.vscode/PythonImportHelper-v2-Completion\.json$
      - id: check-yaml
      - id: check-added-large-files

  # Добавляем black для автоформатирования
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        args: ["--config=pyproject.toml"]

  # Добавляем isort для сортировки импортов (совместим с black)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
# Временно отключаем pytest хуки до решения проблем с зависимостями
# -   repo: local
#     hooks:
#     -   id: pytest-critical
#         name: pytest (критические тесты)
#         entry: pytest
#         args: [tests/unit/core/, -v]
#         language: python  # Вместо system используем python
#         # Расширенный список зависимостей:
#         additional_dependencies: [
#             pytest,
#             pytest-cov,
#             pynput,
#             requests,
#             selenium,
#             pyautogui,
#             numpy,
#             opencv-python,
#             pywin32,
#             pillow,
#             psutil
#         ]
#         pass_filenames: false
#         always_run: true
#         # Настраиваем переменные окружения, чтобы добавить текущий каталог в PYTHONPATH
#         # для правильного импорта модуля 'core'
#         # Примечание: в Windows pre-commit может иметь проблемы с установкой env
#         # если это не сработает, попробуйте другой подход
#         files: ^$  # Не запускать для файлов
#         stages: [pre-commit]

#     -   id: pytest-affected
#         name: pytest (только измененные файлы)
#         entry: python
#         args: [scripts/run_affected_tests.py]
#         language: python  # Вместо system используем python
#         # Для второго хука тоже указываем зависимости:
#         additional_dependencies: [pytest, pytest-cov]
#         pass_filenames: true
#         stages: [pre-commit]
